### ISSUE TITLE
Har vi fortsatt utfordring i avhengigheter?

### ISSUE THREAD

**Issue by ksaehlie** [umglurf/juleol#5]
Reading https://pypi.org/simple/wtforms/
Download error on https://pypi.org/simple/wtforms/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
Couldn't find index page for 'wtforms' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: [Errno -3] Temporary failure in name resolution -- Some packages may not be found!
No local packages or working download links found for wtforms
error: Could not find suitable distribution for Requirement.parse('wtforms')

**Comment by umglurf** [comment]
Sounds like either a temporary dns issue or a local dns issue. 
Tried both new docker build and pip install, both without problems.

Is this error from docker build? Could there be a dns issue with the docker installation?
